#!/usr/bin/env python3
"""Genuine files-provider builds/restores plus hostile archive controls.

Creates one public scratch C port, never a product port. Uses normal manifest
install for every operation; no installed-tree skip or mocked vcpkg execution.
Linux checks do not claim Apple SDK, App or gameplay execution.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import stat
import struct
import subprocess
import sys
import warnings
import zipfile

import ios_public_vcpkg_cache as cache


def check(condition: bool, description: str) -> None:
    if not condition:
        raise AssertionError(description)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vcpkg-root", type=Path, required=True)
    parser.add_argument("--cmake", type=Path, required=True)
    parser.add_argument("--ninja", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    root = args.output_dir.resolve()
    check(not root.exists(), "Use a fresh output directory.")
    root.mkdir(parents=True)
    vcpkg_root = args.vcpkg_root.resolve()
    production_ports = cache.public_ports(Path(__file__).resolve().parents[1], vcpkg_root)
    check({"vcpkg-cmake", "glib", "openssl", "libgdiplus"} <= production_ports,
          "The real production public registry/overlay allowlist rejected required public ports.")
    cc = shutil.which("cc")
    check(cc is not None, "A genuine native C compiler is required.")
    arch = platform.machine()
    check(arch in ("x86_64", "arm64", "aarch64"), "Unsupported native regression architecture.")
    if platform.system() == "Darwin":
        triplet = "x64-osx" if arch == "x86_64" else "arm64-osx"
    else:
        check(platform.system() == "Linux", "Use a native Linux or Mac host.")
        triplet = "x64-linux" if arch == "x86_64" else "arm64-linux"
    port = root / "ports/aether-cache-probe"
    source = port / "source"
    source.mkdir(parents=True)
    (port / "vcpkg.json").write_text(json.dumps({
        "name": "aether-cache-probe", "version": "1.0.0",
        "dependencies": [{"name": "vcpkg-cmake", "host": True}],
        "features": {"extra": {"description": "Public scratch feature control paragraph"}},
    }) + "\n")
    (port / "portfile.cmake").write_text('''vcpkg_cmake_configure(SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}/source")
vcpkg_cmake_install()
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(CREATE_LINK "libcache_probe.a" "${CURRENT_PACKAGES_DIR}/lib/libcache_probe_link.a" SYMBOLIC)
file(CREATE_LINK "libcache_probe.a" "${CURRENT_PACKAGES_DIR}/debug/lib/libcache_probe_link.a" SYMBOLIC)
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/copyright" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
''')
    (port / "copyright").write_text("Public scratch test source, generated by this regression.\n")
    (source / "CMakeLists.txt").write_text('''cmake_minimum_required(VERSION 3.20)
project(cache_probe C)
add_library(cache_probe STATIC cache_probe.c)
install(TARGETS cache_probe ARCHIVE DESTINATION lib)
install(FILES cache_probe.h DESTINATION include)
''')
    (source / "cache_probe.h").write_text("int cache_probe(void);\n")
    manifest = {"name": "public-cache-regression", "version": "1.0.0",
                "dependencies": [{"name": "aether-cache-probe", "features": ["extra"]}]}
    (root / "vcpkg.json").write_text(json.dumps(manifest) + "\n")
    archives = root / "archives"
    env = os.environ.copy()
    env["PATH"] = os.pathsep.join((str(args.cmake.resolve().parent),
                                  str(args.ninja.resolve().parent), env.get("PATH", "")))
    env["VCPKG_FORCE_SYSTEM_BINARIES"] = "1"
    env["VCPKG_BINARY_SOURCES"] = f"clear;files,{archives},readwrite"
    command = [str(vcpkg_root / "vcpkg"), "install", f"--triplet={triplet}",
               f"--host-triplet={triplet}", f"--overlay-ports={root / 'ports'}",
               f"--x-install-root={root / 'installed'}", f"--x-buildtrees-root={root / 'buildtrees'}",
               f"--x-packages-root={root / 'packages'}", f"--downloads-root={root / 'downloads'}",
               "--disable-metrics"]
    ports = {"aether-cache-probe", "vcpkg-cmake"}
    stages = []
    def install(stage: str, expect_success: bool = True) -> str:
        for name in ("installed", "packages", "buildtrees"):
            shutil.rmtree(root / name, ignore_errors=True)
        with (root / f"{stage}.log").open("w") as f:
            rc = subprocess.run(command, cwd=root, env=env, stdout=f, stderr=subprocess.STDOUT).returncode
        check((rc == 0) == expect_success, f"Unexpected genuine vcpkg result in {stage}; inspect its scratch log.")
        report = cache.validate_cache(archives, ports, {triplet})
        (root / f"{stage}-archives.json").write_text(json.dumps(report, indent=2) + "\n")
        stages.append({"stage": stage, "exit_code": rc, "archive_count": report["archive_count"],
                       "content_sha256": report["content_sha256"]})
        return (root / f"{stage}.log").read_text()
    def write_source(value: int) -> None:
        (source / "cache_probe.c").write_text(f'#include "cache_probe.h"\nint cache_probe(void) {{ return {value}; }}\n')
    def execute(value: int) -> str:
        fixture = root / "check.c"
        fixture.write_text(f'#include "cache_probe.h"\nint main(void) {{ return cache_probe() == {value} ? 0 : 1; }}\n')
        library = root / f"installed/{triplet}/lib/libcache_probe.a"
        subprocess.run([cc, str(fixture), "-I", str(root / f"installed/{triplet}/include"),
                        str(library), "-o", str(root / "check")], check=True)
        subprocess.run([str(root / "check")], check=True)
        return cache.digest(library)
    write_source(7)
    first = install("cold-build")
    check("Building aether-cache-probe" in first and "Restored 0 package(s)" in first, "Cold stage did not actually compile.")
    before = cache.validate_cache(archives, ports, {triplet})
    check(before["archive_count"] == 2, "Expected the genuine C port and host helper ZIPs.")
    probe_record = next(a for a in before["archives"] if a["package"] == "aether-cache-probe")
    probe_zip = archives / probe_record["abi"][:2] / (probe_record["abi"] + ".zip")
    with zipfile.ZipFile(probe_zip) as z:
        check("Feature: extra" in z.read("CONTROL").decode(), "Missing genuine feature paragraph.")
        check(any(stat.S_IFMT(i.external_attr >> 16) == stat.S_IFLNK for i in z.infolist()), "The provider did not retain the actual relative package symlink.")
    first_library = execute(7)
    second = install("normal-manifest-restore")
    check("Restored 2 package(s)" in second and "Building aether-cache-probe" not in second,
          "Normal manifest install did not restore both real files-provider archives.")
    check(execute(7) == first_library, "Restored native library bytes changed.")
    write_source(8)
    third = install("changed-port-abi")
    check("Restored 1 package(s)" in third and "Building aether-cache-probe" in third,
          "Changed port content did not genuinely invalidate its ABI.")
    changed = cache.validate_cache(archives, ports, {triplet})
    check(changed["archive_count"] == 3, "ABI change did not preserve the older partial archives.")
    check(execute(8) != first_library, "Changed source did not produce a different native library.")
    fail = root / "ports/aether-cache-failure"
    fail.mkdir()
    (fail / "vcpkg.json").write_text(json.dumps({"name": "aether-cache-failure", "version": "1.0.0",
        "dependencies": [{"name": "aether-cache-probe", "features": ["extra"]}]}) + "\n")
    (fail / "portfile.cmake").write_text('message(FATAL_ERROR "Expected scratch failure after successful dependency build")\n')
    manifest["dependencies"] = ["aether-cache-failure"]
    (root / "vcpkg.json").write_text(json.dumps(manifest) + "\n")
    write_source(9)
    failed = install("later-package-failure", expect_success=False)
    after_failure = cache.validate_cache(archives, ports, {triplet})
    check("Building aether-cache-probe" in failed and after_failure["archive_count"] == 4,
          "Successful package archive was not flushed before normal vcpkg failure.")
    execute(9)

    # Derive rejection controls from a real successfully produced archive.
    controls = root / "rejection-controls"
    controls.mkdir()
    with zipfile.ZipFile(probe_zip) as z:
        original = [(i, z.read(i)) for i in z.infolist()]
    # Standard-library ZIP64 container compatibility, using genuine provider
    # payload bytes. This is a format control, not a claimed large vcpkg build.
    zip64_dir = root / "zip64-format-control" / probe_record["abi"][:2]
    zip64_dir.mkdir(parents=True)
    zip64_path = zip64_dir / probe_zip.name
    with zipfile.ZipFile(zip64_path, "w", allowZip64=True) as z:
        for i, data in original:
            z.writestr(i, data)
        for index in range(65536 - len(original)):
            z.writestr(f"share/aether-cache-probe/zip64-format-{index}", b"")
    check(b"PK\x06\x06" in zip64_path.read_bytes()[-200:], "The format control did not actually produce a ZIP64 end record.")
    check(cache.validate_cache(zip64_dir.parent, ports, {triplet})["archive_count"] == 1,
          "Standard ZIP64 container rejected.")
    rejected = []
    def reject(label: str, edit, expected: str, allowed_triplets=None) -> cache.InvalidCache:
        d = controls / label / probe_record["abi"][:2]
        d.mkdir(parents=True)
        path = d / probe_zip.name
        entries = edit([(i, b) for i, b in original])
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            with zipfile.ZipFile(path, "w") as z:
                for info, data in entries:
                    z.writestr(info, data)
        try:
            cache.validate_cache(d.parent, ports, allowed_triplets or {triplet})
        except cache.InvalidCache as e:
            check(str(e) == expected, f"Wrong rejection reason in {label}.")
            failure = e
            check(len(cache.rejection_message(e)) <= 640, "Rejection diagnostic is not bounded.")
            if expected != "unexpected-package-root":
                check(e.metadata is None, "Unverified package identity was printed in a diagnostic.")
        else:
            raise AssertionError(f"Unsafe control accepted: {label}.")
        rejected.append(label)
        return failure
    def control_edit(old: bytes, new: bytes):
        return lambda es: [(i, b.replace(old, new) if i.filename == "CONTROL" else b) for i, b in es]
    reject("wrong-control-abi", control_edit(probe_record["abi"].encode(), b"0" * 64), "control-abi-mismatch")
    reject("altered-abi-info", lambda es: [(i, b + b"changed\n" if i.filename.endswith("vcpkg_abi_info.txt") else b) for i, b in es], "abi-info-digest-mismatch")
    reject("private-package", control_edit(b"Package: aether-cache-probe", b"Package: private-product"), "non-public-package")
    reject("private-dependency", control_edit(b"Depends: vcpkg-cmake", b"Depends: private-product"), "non-public-dependency")
    reject("foreign-triplet", lambda es: es, "unexpected-package-triplet", {"arm64-ios"})
    reject("path-traversal", lambda es: es + [(zipfile.ZipInfo("../outside"), b"x")], "unsafe-member")
    reject("absolute-path", lambda es: es + [(zipfile.ZipInfo("/outside"), b"x")], "unsafe-member")
    reject("duplicate-control", lambda es: es + [next(e for e in es if e[0].filename == "CONTROL")], "duplicate-member")
    def link_edit(target: bytes):
        def edit(es):
            i = zipfile.ZipInfo("lib/unsafe-link")
            i.create_system = 3
            i.external_attr = (stat.S_IFLNK | 0o777) << 16
            return es + [(i, target)]
        return edit
    reject("absolute-symlink", link_edit(b"/outside"), "unsafe-symlink")
    reject("escaping-symlink", link_edit(b"../../outside"), "escaping-symlink")
    reject("symlink-cycle", link_edit(b"unsafe-link"), "symlink-cycle")
    reject("source-cache-root", lambda es: es + [(zipfile.ZipInfo("buildtrees/compiler.log"), b"x")], "unexpected-package-root")
    known_root = reject("diagnostic-known-root", lambda es: es + [
        (zipfile.ZipInfo("manual-tools/aether-cache-probe/tool"), b"x")], "unexpected-package-root")
    check(known_root.metadata == {"abi": probe_record["abi"], "package": "aether-cache-probe",
                                  "triplet": triplet, "root": "manual-tools"},
          "Known root diagnostic did not contain only verified public identity and the fixed label.")
    private_root = "private-root-name-must-not-be-echoed"
    unknown_root = reject("diagnostic-hashed-root", lambda es: es + [
        (zipfile.ZipInfo(private_root + "/private-member-must-not-be-echoed"), b"x")], "unexpected-package-root")
    message = cache.rejection_message(unknown_root)
    check(private_root not in message and "private-member-must-not-be-echoed" not in message,
          "Arbitrary root/member text escaped into a diagnostic.")
    check(unknown_root.metadata == {"abi": probe_record["abi"], "package": "aether-cache-probe",
          "triplet": triplet, "root_sha256": hashlib.sha256(private_root.encode()).hexdigest()},
          "Unknown root diagnostic was not limited to verified identity and a digest.")
    # Run the real CLI rejection path, without substituting an Apple identity.
    # Linux rejects the host boundary; Mac rejects this private CONTROL after
    # using its actual SDK identity. Neither may publish success outputs/report.
    output = root / "rejected-github-output"
    output.write_text("existing-test-marker=value\n")
    rejection_report = root / "must-not-exist.json"
    rejected_cli = subprocess.run([
        sys.executable, str(Path(cache.__file__).resolve()), "validate",
        "--repository", str(Path(__file__).resolve().parents[1]),
        "--vcpkg-root", str(vcpkg_root), "--sdk", "iphonesimulator",
        "--triplet", "arm64-ios-simulator", "--internal", "OFF",
        "--cache-dir", str(controls / "private-package"),
        "--report", str(rejection_report), "--github-output", str(output),
    ], env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    expected_code = "non-public-package" if platform.system() == "Darwin" else "real-apple-host-required"
    check(rejected_cli.returncode == 1 and expected_code in rejected_cli.stderr,
          "Actual CLI did not reject the unsafe cache at the genuine platform/package boundary.")
    check(not rejected_cli.stdout and output.read_text() == "existing-test-marker=value\n"
          and not rejection_report.exists(), "Rejected CLI cache published success output or a report.")
    # Actual provider bytes with an oversized declared central directory must
    # be rejected before zipfile allocates/parses that directory.
    cd_dir = controls / "central-directory-budget" / probe_record["abi"][:2]
    cd_dir.mkdir(parents=True)
    cd_path = cd_dir / probe_zip.name
    payload = bytearray(probe_zip.read_bytes())
    end = payload.rfind(b"PK\x05\x06")
    struct.pack_into("<L", payload, end + 12, cache.MAX_CENTRAL_DIRECTORY_BYTES + 1)
    cd_path.write_bytes(payload)
    try:
        cache.validate_cache(cd_dir.parent, ports, {triplet})
    except cache.InvalidCache as e:
        check(str(e) == "central-directory-too-large", "Central-directory allocation was not gated early.")
        rejected.append("central-directory-budget")
    else:
        raise AssertionError("Oversized central directory accepted.")
    # ZIP64 metadata overrides a non-sentinel ordinary EOCD too. Derive the
    # reviewer's allocation-bypass control from actual provider archive bytes;
    # inspect only stdlib end records, never parse/decompress its oversized CD.
    nonsentinel_dir = controls / "nonsentinel-zip64-budget" / probe_record["abi"][:2]
    nonsentinel_dir.mkdir(parents=True)
    nonsentinel_path = nonsentinel_dir / probe_zip.name
    payload = probe_zip.read_bytes()
    end = payload.rfind(b"PK\x05\x06")
    fields = struct.unpack("<4s4H2LH", payload[end:end + 22])
    count, old_cd_size, cd_offset = fields[4:7]
    check(count != 0xffff and old_cd_size < cache.MAX_CENTRAL_DIRECTORY_BYTES,
          "The original provider EOCD is not a non-sentinel control.")
    check(cd_offset + old_cd_size == end, "Unexpected original provider CD layout.")
    new_cd_size = cache.MAX_CENTRAL_DIRECTORY_BYTES + 1
    padding = new_cd_size - old_cd_size
    zip64_offset = end + padding
    record = struct.pack("<4sQ2H2L4Q", b"PK\x06\x06", 44, 45, 45, 0, 0,
                         count, count, new_cd_size, cd_offset)
    locator = struct.pack("<4sLQL", b"PK\x06\x07", 0, zip64_offset, 1)
    nonsentinel_path.write_bytes(payload[:end] + bytes(padding) + record + locator + payload[end:])
    with nonsentinel_path.open("rb") as f:
        end_metadata = zipfile._EndRecData(f)
    check(end_metadata[zipfile._ECD_SIZE] == new_cd_size,
          "The stdlib did not actually adopt the non-sentinel ZIP64 size.")
    try:
        cache.validate_cache(nonsentinel_dir.parent, ports, {triplet})
    except cache.InvalidCache as e:
        check(str(e) == "central-directory-too-large", "Non-sentinel ZIP64 bypass was not rejected before parsing.")
        rejected.append("nonsentinel-zip64-budget")
    else:
        raise AssertionError("Non-sentinel ZIP64 budget bypass accepted.")
    # A small, legal non-sentinel ZIP64 container retains all provider payload
    # bytes and remains accepted; sentinel fields without a locator do not.
    small_dir = root / "nonsentinel-zip64-format-control" / probe_record["abi"][:2]
    small_dir.mkdir(parents=True)
    small_path = small_dir / probe_zip.name
    record = struct.pack("<4sQ2H2L4Q", b"PK\x06\x06", 44, 45, 45, 0, 0,
                         count, count, old_cd_size, cd_offset)
    locator = struct.pack("<4sLQL", b"PK\x06\x07", 0, end, 1)
    small_path.write_bytes(payload[:end] + record + locator + payload[end:])
    check(cache.validate_cache(small_dir.parent, ports, {triplet})["archive_count"] == 1,
          "Legal small non-sentinel ZIP64 container rejected.")
    missing_dir = controls / "zip64-missing-locator" / probe_record["abi"][:2]
    missing_dir.mkdir(parents=True)
    missing = bytearray(payload)
    struct.pack_into("<HH", missing, end + 8, 0xffff, 0xffff)
    (missing_dir / probe_zip.name).write_bytes(missing)
    try:
        cache.validate_cache(missing_dir.parent, ports, {triplet})
    except cache.InvalidCache as e:
        check(str(e) == "invalid-zip64-end", "Missing ZIP64 locator was not rejected.")
        rejected.append("zip64-missing-locator")
    else:
        raise AssertionError("ZIP64 sentinel without locator accepted.")
    # Exercise whole-cache budgets against the real multi-archive snapshot.
    for setting, value, expected in (
        ("MAX_CACHE_EXPANDED_BYTES", 1, "cache-expanded-size"),
        ("MAX_CACHE_MEMBERS", 1, "cache-member-count"),
        ("MAX_ARCHIVES", 1, "cache-archive-count"),
    ):
        old_limit = getattr(cache, setting)
        setattr(cache, setting, value)
        try:
            try:
                cache.validate_cache(archives, ports, {triplet})
            except cache.InvalidCache as e:
                check(str(e) == expected, f"Whole-cache budget not enforced: {setting}.")
                rejected.append(setting.lower())
            else:
                raise AssertionError(f"Whole-cache budget ignored: {setting}.")
        finally:
            setattr(cache, setting, old_limit)
    # Damage an actual compressed payload without changing its recorded CRC.
    crc_dir = controls / "bad-crc" / probe_record["abi"][:2]
    crc_dir.mkdir(parents=True)
    crc_path = crc_dir / probe_zip.name
    shutil.copyfile(probe_zip, crc_path)
    with zipfile.ZipFile(crc_path) as z:
        i = next(i for i in z.infolist() if i.filename == "lib/libcache_probe.a")
        offset = i.header_offset
    with crc_path.open("r+b") as f:
        f.seek(offset + 26)
        n, extra = struct.unpack("<HH", f.read(4))
        pos = offset + 30 + n + extra
        f.seek(pos)
        byte = f.read(1)
        f.seek(pos)
        f.write(bytes([byte[0] ^ 0xff]))
    try:
        cache.validate_cache(crc_dir.parent, ports, {triplet})
    except cache.InvalidCache as e:
        check(str(e) == "invalid-zip-payload", "Wrong rejection reason for actual damaged compressed bytes.")
        rejected.append("bad-crc")
    else:
        raise AssertionError("Corrupt genuine payload accepted.")
    result = {"status": "passed", "vcpkg_version": cache.run([str(vcpkg_root / "vcpkg"), "version"]),
              "validator_sha256": cache.digest(Path(cache.__file__)),
              "test_sha256": cache.digest(Path(__file__)),
              "vcpkg_head": cache.run(["git", "rev-parse", "HEAD"], vcpkg_root),
              "cmake_version": cache.run([str(args.cmake.resolve()), "--version"]),
              "compiler_version": cache.run([cc, "--version"]), "triplet": triplet,
              "actual_manifest_install": True, "cold_compile": "passed", "native_api_execution": "passed",
              "files_provider_restore": "passed", "changed_port_abi": "passed", "partial_failure_flush": "passed",
              "package_symlink": "passed", "rejected_controls": rejected, "stages": stages,
              "zip64_container_compatibility": "passed",
              "nonsentinel_zip64_container_compatibility": "passed",
              "production_public_port_allowlist": "passed",
              "bounded_root_diagnostics": "passed", "rejection_does_not_publish_success": "passed",
              "apple_sdk_cache": "not_run", "app": "not_run", "gameplay": "not_run"}
    (root / "evidence.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps({k: result[k] for k in ("status", "files_provider_restore", "changed_port_abi", "partial_failure_flush", "apple_sdk_cache", "app", "gameplay")}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
